### ISSUE TITLE
Cannot be configured on Chimera

### ISSUE THREAD

**Issue by ayechief** [PoomSmart/BlockEmAll#1]
![image](https://user-images.githubusercontent.com/10886930/63592136-27da1e00-c5b1-11e9-815e-79072fc01fa3.jpeg)
![image](https://user-images.githubusercontent.com/10886930/63592152-31638600-c5b1-11e9-962f-c71c0fcc70d6.jpeg)

Hey, as you can see on the screenshots I tried to use both Sileo and Zebra and it just doesn't work. I can't even make that `_apt` account because there is such command as `adduser`

**Comment by PoomSmart** [comment]
Fixed in 0.0.2.2
